version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000"  # only expose internally, not to host
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - trivia-network

  frontend:
    build: ./frontend
    expose:
      - "80"  # only expose internally
    depends_on:
      - backend
    networks:
      - trivia-network

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"  # still mapped for dev mode
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - trivia-network
    profiles:
      - dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # only nginx is exposed to host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - trivia-network

networks:
  trivia-network:
    driver: bridge
