version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - trivia-network

  frontend-build:
    build: ./frontend
    command: npm run build
    volumes:
      - ./frontend:/app
    networks:
      - trivia-network
    profiles:
      - build

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"  # still mapped for dev mode
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - trivia-network
    profiles:
      - dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"  # host port 3000 -> container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-build
    networks:
      - trivia-network

networks:
  trivia-network:
    driver: bridge

