version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=*
      - NODE_ENV=production
    expose:
      - "8000"
    networks:
      - trivia-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - trivia-network

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - trivia-network
    profiles:
      - dev

networks:
  trivia-network:
    driver: bridge